import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://t50008-s50013.sb.gdev09.gcp.kibocommerce.com/user/login');
  await expect(page.locator('form[name="mz-loginform"]')).toContainText('Login with One-Time Password');
  await page.getByRole('link', { name: 'Login with One-Time Password' }).click();
  await expect(page.locator('form[name="mz-loginform"]')).toContainText('Email Address');
  await expect(page.locator('form[name="mz-loginform"]')).toContainText('Request Code');
  await page.getByRole('link', { name: '← Back to Password Login' }).click();
  await page.getByRole('link', { name: 'Login with One-Time Password' }).click();
  await expect(page.locator('form[name="mz-loginform"]')).toContainText('Back to Password Login');
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('rohan.birla');
  await page.getByRole('textbox').press('ArrowUp');
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('rohan.bi@test.com');
  await page.getByRole('button', { name: 'Request Code' }).click();
  await expect(page.locator('form[name="mz-loginform"]')).toContainText('Failed to send code. Please try again.');
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('rohan.birla@test.com');
  await page.getByRole('button', { name: 'Request Code' }).click();
  await expect(page.locator('form[name="mz-loginform"]')).toContainText('Verification Code');
  await expect(page.locator('form[name="mz-loginform"]')).toContainText('If an account with that email address exists, a code has been sent to it.');
  await expect(page.locator('form[name="mz-loginform"]')).toContainText('Resend Code');
  await expect(page.locator('form[name="mz-loginform"]')).toContainText('Back to Password Login');
  await page.getByRole('textbox', { name: 'Verification Code' }).click();
  await page.getByRole('textbox', { name: 'Verification Code' }).fill('123456');
  await expect(page.locator('form[name="mz-loginform"]')).toContainText('The code you entered is incorrect. Please try again.');
  await page.getByRole('textbox', { name: 'Verification Code' }).click();
  await page.getByRole('textbox', { name: 'Verification Code' }).fill('123456');
  await page.getByRole('textbox', { name: 'Verification Code' }).click();
  await page.getByRole('textbox', { name: 'Verification Code' }).fill('123456');
  await expect(page.locator('form[name="mz-loginform"]')).toContainText('Too many attempts. Please request a new code.');
  await expect(page.locator('form[name="mz-loginform"]')).toContainText('Request New Code');
  await page.getByRole('link', { name: 'Request New Code' }).click();
});